language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.26.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - export version=$(date '+%s') 

install:
  - docker-compose -f deployment/docker/docker-compose-build.yaml build --parallel
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f deployment/docker/docker-compose-build.yaml push
  # - docker tag udagram-users bobbyjenrow/udagram-users
  # - docker push bobbyjenrow/udagram-users
  # - docker tag udagram-feed bobbyjenrow/udagram-feed
  # - docker push bobbyjenrow/udagram-feed
  # - docker tag udagram-reverseproxy bobbyjenrow/udagram-reverseproxy
  # - docker push bobbyjenrow/udagram-reverseproxy
  # - docker tag udagram-frontend bobbyjenrow/udagram-frontend
  # - docker push bobbyjenrow/udagram-frontend