version: "3"
services:
  reverseproxy:
    build:
      context: ../../reverseproxy
    image: udagram-reverseproxy 
  backend_user:
    build:
      context: ../../backend-user
    image: udagram-users
  backend_feed:
    build:
      context: ../../backend-feed  
    image: udagram-feed
  frontend:
    build:
      context: ../../frontend  
    image: udagram-frontend